In [1]:
import numpy as np
arr=np.array([])
print(arr)


[]


In [2]:
print(type(arr))#Empty array

<class 'numpy.ndarray'>


In [4]:
#Array with value
import numpy as np
arr=np.array([20,30,40])
print(arr)

[20 30 40]


## 1D Array

In [5]:
import numpy as np
arr=np.array([20,30,40])
print("Dimension of array is",arr.ndim)

Dimension of array is 1


In [6]:
print(arr.size)

3


In [7]:
print(arr.dtype)

int64


## 2D Array

In [11]:
arra_2d=np.array([[2,3,4],[5,6,7],[6,0,7]])
print(arra_2d)

[[2 3 4]
 [5 6 7]
 [6 0 7]]


## 3D Array

In [9]:
import numpy as np

# Create a 3D array with shape (2, 2, 3)
# This represents 2 "slices" or "matrices", each with 2 rows and 3 columns.
arr_3d = np.array([
    [[1, 2, 3],
     [4, 5, 6]],

    [[7, 8, 9],
     [10, 11, 12]]
])

print(arr_3d)
print("Shape of the array:", arr_3d.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape of the array: (2, 2, 3)


In [10]:
import numpy as np
arr=np.array([[[1,2,3],[1,2,3],[2,3,4]]])
print(arr)

[[[1 2 3]
  [1 2 3]
  [2 3 4]]]


## Built-in-Functions in to generate numpy array

## 1.arange(): 

In [11]:
np.arange(10) #it will print first 10 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.ones(3)

array([1., 1., 1.])

##  2.ones():

In [14]:
np.ones(3)# 1D array

array([1., 1., 1.])

In [16]:
np.ones((2,2))# 2D array

array([[1., 1.],
       [1., 1.]])

In [17]:
np.ones(3,3)

TypeError: Cannot interpret '3' as a data type

In [25]:
a=np.ones((5,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## 3.Zeros

In [26]:
np.zeros(3)

array([0., 0., 0.])

In [33]:
import numpy as np
arr=np.array([[1,2,3],[3,4,5],[3,4,5],[3,2,1]])
print(arr)

[[1 2 3]
 [3 4 5]
 [3 4 5]
 [3 2 1]]


## 4.eye()---->Identity

In [35]:
np.eye(3) #Diagonal elements are 1 and all other  are 0

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## 5.full()-->Used to generate array same elements

In [40]:
np.full(2,2,2)

TypeError: Cannot interpret '2' as a data type

In [44]:
np.full((3,3),10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [48]:
np.full((4,3,),20)

array([[20, 20, 20],
       [20, 20, 20],
       [20, 20, 20],
       [20, 20, 20]])

## 6.linspace

In [2]:
import numpy as np
np.linspace(1,1000)


array([   1.        ,   21.3877551 ,   41.7755102 ,   62.16326531,
         82.55102041,  102.93877551,  123.32653061,  143.71428571,
        164.10204082,  184.48979592,  204.87755102,  225.26530612,
        245.65306122,  266.04081633,  286.42857143,  306.81632653,
        327.20408163,  347.59183673,  367.97959184,  388.36734694,
        408.75510204,  429.14285714,  449.53061224,  469.91836735,
        490.30612245,  510.69387755,  531.08163265,  551.46938776,
        571.85714286,  592.24489796,  612.63265306,  633.02040816,
        653.40816327,  673.79591837,  694.18367347,  714.57142857,
        734.95918367,  755.34693878,  775.73469388,  796.12244898,
        816.51020408,  836.89795918,  857.28571429,  877.67346939,
        898.06122449,  918.44897959,  938.83673469,  959.2244898 ,
        979.6122449 , 1000.        ])

## Random

## 1.randint()

In [18]:

np.random.randint(1,1000,5)

array([994, 970, 274, 574, 727], dtype=int32)

In [23]:
np.random.randint(1,20,size=(3,3))

array([[19, 13,  4],
       [ 5,  5, 15],
       [16, 15, 19]], dtype=int32)

In [24]:
np.random.randint(2,200,size=(2,3))

array([[ 66,  73,  63],
       [ 50, 169, 138]], dtype=int32)

## 2.rand() :-used to generate random  numbers between 0 to 1

In [26]:
np.random.rand(10) #it will generate 10 random numbers between 0 to 1

array([0.95773767, 0.3792742 , 0.87048544, 0.90413636, 0.37694177,
       0.70551251, 0.52940128, 0.75806606, 0.50952677, 0.60733144])

In [27]:
#create 2D array of order (4,4) with random nubers between 0 to 1
np.random.rand(4,4)

array([[0.65493652, 0.3838743 , 0.07308926, 0.8603614 ],
       [0.33820053, 0.87366488, 0.59437985, 0.90185549],
       [0.61838677, 0.40141054, 0.47597093, 0.2846966 ],
       [0.71042899, 0.95234129, 0.95047459, 0.57920531]])

In [28]:
np.random.rand(7,3)

array([[0.18290615, 0.92249558, 0.11385402],
       [0.18034905, 0.98392116, 0.89863786],
       [0.9804595 , 0.12072003, 0.99318798],
       [0.12320631, 0.82879833, 0.64029438],
       [0.0187202 , 0.55280934, 0.05035711],
       [0.56093705, 0.13262429, 0.71978749],
       [0.04037086, 0.97689355, 0.60137881]])

## 3.randn():It is use to generate random numbers from normal distribution within a range (-3 to 3)

In [29]:
np.random.randn(3) #This is 1D array

array([-1.03655426,  1.14702633,  1.72914667])

In [30]:
np.random.randn(2,3) #2D array

array([[ 0.19727204,  0.85794872,  1.13708367],
       [ 0.10643827, -1.19947197,  0.22753845]])

In [38]:
#Finding maximun value of the array
array=np.random.randint(1,10000,10)
print(array)
np.max(array)#

[2659 2340 1502 7168 9582 5846 4401 5422   64 6374]


np.int32(9582)

In [40]:
np.argmax(array) #Use to find the indexing of the maximum value

np.int64(4)

In [42]:
np.min(array)
np.argmin(array)

np.int64(8)

## Indexing

In [48]:
a=np.arange(20,30)
print(a)


[20 21 22 23 24 25 26 27 28 29]


In [50]:
print(a[3])

23


## Slicing

In [52]:
a[3:8]


array([23, 24, 25, 26, 27])

In [53]:
a[::-1]# It will reverse the array

array([29, 28, 27, 26, 25, 24, 23, 22, 21, 20])

## Indexing with 2D array

In [55]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [61]:
a[[0,1]] #fetching 1st and 2nd row NOTE:double [[ ]] are important

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
a[[1]]

array([[4, 5, 6]])

In [62]:
a[[1,0]] 

array([[4, 5, 6],
       [1, 2, 3]])

In [67]:
a[1]

array([4, 5, 6])

In [69]:
a[0][2] #fetching single element

np.int64(3)

In [71]:
a[:][1] #fetching all element of 1st column

array([4, 5, 6])

In [72]:
a[:][:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [74]:
a[:,2] #fetching a specific column

array([3, 6, 9])

a

In [77]:
a[2,2]

array([[7, 8, 9],
       [7, 8, 9]])

In [82]:
a[1,2]

np.int64(6)

In [88]:
a[:][1]

array([4, 5, 6])

In [89]:
a[:,2]

array([3, 6, 9])